// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/my-island.glb -t -o components/models/MyIsland.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TV_2_0_1: THREE.Mesh
    TV_2_0_2: THREE.Mesh
    TV_2_0_3: THREE.Mesh
    Water_low: THREE.Mesh
    Cone: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
    Cube004_2: THREE.Mesh
    Water_high: THREE.Mesh
    Rock_1: THREE.Mesh
    Rock_2: THREE.Mesh
    Rock_3: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder018_1: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder018_1: THREE.Mesh
    Cylinder025: THREE.Mesh
    Cylinder025_1: THREE.Mesh
    Cylinder028: THREE.Mesh
    Cylinder028_1: THREE.Mesh
    Plant_3: THREE.Mesh
    Plant_4: THREE.Mesh
    Cube082: THREE.Mesh
    Cube082_1: THREE.Mesh
    Cube082_2: THREE.Mesh
    Cube082_3: THREE.Mesh
    Cube081: THREE.Mesh
    Cube081_1: THREE.Mesh
    Cube081_2: THREE.Mesh
    Cube081_3: THREE.Mesh
    Cube089: THREE.Mesh
    Cube089_1: THREE.Mesh
    Cube090: THREE.Mesh
    Cube090_1: THREE.Mesh
    Cube090_2: THREE.Mesh
    Grass: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder009_1: THREE.Mesh
    Cylinder009_2: THREE.Mesh
    Cube021: THREE.Mesh
    Cube021_1: THREE.Mesh
    Rock_6: THREE.Mesh
    Cube019: THREE.Mesh
    Cube019_1: THREE.Mesh
    Cube019: THREE.Mesh
    Cube019_1: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder064: THREE.Mesh
    Cylinder064_1: THREE.Mesh
    Cylinder064_2: THREE.Mesh
    Cylinder062: THREE.Mesh
    Cylinder062_1: THREE.Mesh
    Cylinder062_2: THREE.Mesh
    Plant_4001: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder010_1: THREE.Mesh
    Cube070: THREE.Mesh
    Cube070_1: THREE.Mesh
    Cube070_2: THREE.Mesh
    Cube070_3: THREE.Mesh
    Cube080: THREE.Mesh
    Cube080_1: THREE.Mesh
    Cube080_2: THREE.Mesh
    Cube080_3: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder011_1: THREE.Mesh
    Cylinder011_2: THREE.Mesh
    Cylinder011_3: THREE.Mesh
    Cylinder011_4: THREE.Mesh
    Plane029: THREE.Mesh
    Plane029_1: THREE.Mesh
    Plane029_2: THREE.Mesh
    Grass001: THREE.Mesh
    Grass002: THREE.Mesh
    Grass003: THREE.Mesh
    Cube044: THREE.Mesh
    Cube044_1: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder061: THREE.Mesh
    Cylinder061_1: THREE.Mesh
    Cylinder061_2: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cylinder_3: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cylinder020_1: THREE.Mesh
    Cylinder020_2: THREE.Mesh
    Cylinder020_3: THREE.Mesh
    Low_Poly_Watchtower: THREE.Mesh
    Instrument_Guitar_Ultra_Low_Poly: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
    Handpainted_ladder: THREE.Mesh
    Office_desk_ComputerDesk_0: THREE.Mesh
    Cube000_ComputerDesk_0: THREE.Mesh
    Object_2: THREE.Mesh
    Object_2_1: THREE.Mesh
    Object_2_2: THREE.Mesh
    Object_2_3: THREE.Mesh
    Monitor: THREE.Mesh
    Low_Poly_Coffee_table: THREE.Mesh
    ['Low_Poly,_Old-Style_Couch']: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube002_2: THREE.Mesh
    Cube_Latern_01_M_0_1: THREE.Mesh
    Cube_Latern_01_M_0_2: THREE.Mesh
    Cube_Latern_01_M_0_3: THREE.Mesh
    Cube_Latern_01_M_0_4: THREE.Mesh
    Cube_Latern_01_M_0_5: THREE.Mesh
    Cube_Latern_01_M_0_1: THREE.Mesh
    Cube_Latern_01_M_0_2: THREE.Mesh
    Cube_Latern_01_M_0_3: THREE.Mesh
    Cube_Latern_01_M_0_4: THREE.Mesh
    Cube_Latern_01_M_0_5: THREE.Mesh
    ['Chair_-_low_poly']: THREE.Mesh
    Low_Poly_Lantern: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube: THREE.Mesh
    Object_1: THREE.Mesh
    Object_1_1: THREE.Mesh
    Object_1_2: THREE.Mesh
    Object_1_3: THREE.Mesh
    Object_1_4: THREE.Mesh
  }
  materials: {
    ['tv-onyx']: THREE.MeshStandardMaterial
    ['tv-grey']: THREE.MeshStandardMaterial
    ['tv-white']: THREE.MeshStandardMaterial
    Water: THREE.MeshPhysicalMaterial
    Ground: THREE.MeshStandardMaterial
    Surface: THREE.MeshStandardMaterial
    Pathway: THREE.MeshStandardMaterial
    ['Rock.002']: THREE.MeshStandardMaterial
    ['Rock.001']: THREE.MeshStandardMaterial
    Rock: THREE.MeshStandardMaterial
    ['Green.001']: THREE.MeshStandardMaterial
    Pink: THREE.MeshStandardMaterial
    ['Wood.002']: THREE.MeshStandardMaterial
    ['Green.002']: THREE.MeshStandardMaterial
    ['Wood.004']: THREE.MeshStandardMaterial
    ['Green.005']: THREE.MeshStandardMaterial
    ['Wood.005']: THREE.MeshStandardMaterial
    ['Green.006']: THREE.MeshStandardMaterial
    ['DarkGreen.004']: THREE.MeshStandardMaterial
    ['Green.007']: THREE.MeshStandardMaterial
    ['White.003']: THREE.MeshStandardMaterial
    ['Black.003']: THREE.MeshStandardMaterial
    ['Orange.004']: THREE.MeshStandardMaterial
    ['LightOrange.003']: THREE.MeshStandardMaterial
    ['White.004']: THREE.MeshStandardMaterial
    ['Black.004']: THREE.MeshStandardMaterial
    ['Orange.005']: THREE.MeshStandardMaterial
    ['LightOrange.004']: THREE.MeshStandardMaterial
    ['Wood.001']: THREE.MeshStandardMaterial
    ['Orange.003']: THREE.MeshStandardMaterial
    ['Wood.003']: THREE.MeshStandardMaterial
    ['Orange.006']: THREE.MeshStandardMaterial
    ['LightOrange.005']: THREE.MeshStandardMaterial
    ['Green.008']: THREE.MeshStandardMaterial
    ['Wood.006']: THREE.MeshStandardMaterial
    LightWood: THREE.MeshStandardMaterial
    Fire: THREE.MeshStandardMaterial
    ['Rock.003']: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    ['Rock.004']: THREE.MeshStandardMaterial
    ['Rock.005']: THREE.MeshStandardMaterial
    ['moss.green']: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    ['Green.011']: THREE.MeshStandardMaterial
    ['Wood.007']: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    ['LightWood.001']: THREE.MeshStandardMaterial
    ['Wood.008']: THREE.MeshStandardMaterial
    ['Orange.001']: THREE.MeshStandardMaterial
    LightOrange: THREE.MeshStandardMaterial
    ['Green.012']: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    ['Pink.001']: THREE.MeshStandardMaterial
    ['Wood.009']: THREE.MeshStandardMaterial
    ['Green.013']: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    ['Green.014']: THREE.MeshStandardMaterial
    ['DarkGreen.005']: THREE.MeshStandardMaterial
    ['White.001']: THREE.MeshStandardMaterial
    ['Black.001']: THREE.MeshStandardMaterial
    ['Orange.002']: THREE.MeshStandardMaterial
    ['LightWood.003']: THREE.MeshStandardMaterial
    ['Wood.010']: THREE.MeshStandardMaterial
    ['Green.015']: THREE.MeshStandardMaterial
    Mushroom_Top: THREE.MeshStandardMaterial
    Mushroom_Bottom: THREE.MeshStandardMaterial
    ['DarkGreen.006']: THREE.MeshStandardMaterial
    ['Green.016']: THREE.MeshStandardMaterial
    Cyan: THREE.MeshStandardMaterial
    ['Yellow.001']: THREE.MeshStandardMaterial
    ['Green.018']: THREE.MeshStandardMaterial
    ['Green.017']: THREE.MeshStandardMaterial
    ['Berry.002']: THREE.MeshStandardMaterial
    ['Wood.013']: THREE.MeshStandardMaterial
    ['Green.019']: THREE.MeshStandardMaterial
    ['Wood.014']: THREE.MeshStandardMaterial
    ['Orange.007']: THREE.MeshStandardMaterial
    ['LightOrange.001']: THREE.MeshStandardMaterial
    ['Wood.012']: THREE.MeshStandardMaterial
    ['Mushroom_Top.001']: THREE.MeshStandardMaterial
    ['Mushroom_Bottom.001']: THREE.MeshStandardMaterial
    DarkWood: THREE.MeshStandardMaterial
    ['Black.005']: THREE.MeshStandardMaterial
    LightGreen: THREE.MeshStandardMaterial
    ['Green.009']: THREE.MeshStandardMaterial
    Atlas: THREE.MeshStandardMaterial
    Meshessipropinstrumentguitar041Mtl: THREE.MeshStandardMaterial
    ['Wood.015']: THREE.MeshStandardMaterial
    ['LightWood.004']: THREE.MeshStandardMaterial
    String: THREE.MeshStandardMaterial
    ['ladder-brown']: THREE.MeshStandardMaterial
    ComputerDesk: THREE.MeshStandardMaterial
    desktop_glass: THREE.MeshPhysicalMaterial
    desktop_case: THREE.MeshStandardMaterial
    desktop_fans: THREE.MeshStandardMaterial
    desktop_parts: THREE.MeshStandardMaterial
    Monitor: THREE.MeshStandardMaterial
    base_color: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Lovsamling-pages']: THREE.MeshStandardMaterial
    ['lovsamling-image-text']: THREE.MeshStandardMaterial
    ['lovsamling-red']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    Chair: THREE.MeshStandardMaterial
    ['LANTERN_MAT_FINAL.002']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Jens Osberg - farger']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

// Export a named type alias for external consumers
export type MyIslandGLTF = GLTFResult

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/my-island.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[12.341, 1.903, 8.932]} rotation={[-1.548, 0.058, -0.92]} scale={[0.526, 0.012, 0.272]}>
        <group position={[1.036, 76.733, -0.188]}>
          <mesh geometry={nodes.TV_2_0_1.geometry} material={materials['tv-onyx']} />
          <mesh geometry={nodes.TV_2_0_2.geometry} material={materials['tv-grey']} />
          <mesh geometry={nodes.TV_2_0_3.geometry} material={materials['tv-white']} />
        </group>
      </group>
      <mesh geometry={nodes.Water_low.geometry} material={materials.Water} position={[1.49, 0.734, 6.921]} scale={[5.76, 0.244, 4.422]} />
      <mesh geometry={nodes.Cone.geometry} material={materials.Ground} position={[-0.113, -3.926, -0.069]} />
      <group position={[1.035, -0.416, -0.95]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Ground} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Surface} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Pathway} />
      </group>
      <mesh geometry={nodes.Water_high.geometry} material={materials.Water} position={[10.472, 5.212, 6.949]} scale={[4.385, 2.5, 2.786]} />
      <mesh geometry={nodes.Rock_1.geometry} material={materials['Rock.002']} position={[8.086, 3.599, -6.714]} rotation={[-0.016, 0, -0.074]} scale={2.603} />
      <mesh geometry={nodes.Rock_2.geometry} material={materials['Rock.001']} position={[4.451, 3.522, -13.436]} rotation={[-0.016, 0, -0.009]} scale={8.497} />
      <mesh geometry={nodes.Rock_3.geometry} material={materials.Rock} position={[8.797, 3.322, -13.018]} rotation={[-0.032, 0, -0.024]} scale={3.428} />
      <group position={[1.849, 0.963, 5.872]} rotation={[0.006, 0, -0.003]}>
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['Green.001']} />
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.Pink} />
      </group>
      <group position={[-0.795, 0.967, 9.174]} rotation={[-0.004, 0, 0.01]}>
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['Green.001']} />
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.Pink} />
      </group>
      <group position={[-12.039, 0.978, -13.429]} rotation={[0.015, 0, 0.076]}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Wood.002']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[13.345, 5.482, 0.465]} rotation={[0.038, 0, -0.032]}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Wood.002']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[10.447, 5.249, 10.755]} rotation={[0.063, 0, 0.018]}>
        <mesh geometry={nodes.Cylinder025.geometry} material={materials['Wood.004']} />
        <mesh geometry={nodes.Cylinder025_1.geometry} material={materials['Green.005']} />
      </group>
      <group position={[11.41, 5.138, 12.923]} rotation={[0.063, 0, 0.018]}>
        <mesh geometry={nodes.Cylinder028.geometry} material={materials['Wood.005']} />
        <mesh geometry={nodes.Cylinder028_1.geometry} material={materials['Green.006']} />
      </group>
      <mesh geometry={nodes.Plant_3.geometry} material={materials['DarkGreen.004']} position={[-8.133, 0.963, 10.814]} rotation={[0.04, 0, 0.083]} />
      <mesh geometry={nodes.Plant_4.geometry} material={materials['Green.007']} position={[-6.917, 1.269, -7.425]} rotation={[0.015, -0.002, 0.076]} />
      <group position={[-5.49, 1.434, -8.291]} rotation={[-0.05, 0, 0.056]}>
        <mesh geometry={nodes.Cube082.geometry} material={materials['White.003']} />
        <mesh geometry={nodes.Cube082_1.geometry} material={materials['Black.003']} />
        <mesh geometry={nodes.Cube082_2.geometry} material={materials['Orange.004']} />
        <mesh geometry={nodes.Cube082_3.geometry} material={materials['LightOrange.003']} />
      </group>
      <group position={[-8.233, 1.118, -11.855]} rotation={[-0.05, 0, 0.01]} scale={1.224}>
        <mesh geometry={nodes.Cube081.geometry} material={materials['White.004']} />
        <mesh geometry={nodes.Cube081_1.geometry} material={materials['Black.004']} />
        <mesh geometry={nodes.Cube081_2.geometry} material={materials['Orange.005']} />
        <mesh geometry={nodes.Cube081_3.geometry} material={materials['LightOrange.004']} />
      </group>
      <group position={[-11.796, 0.999, -6.486]} rotation={[-0.027, 0, 0.075]}>
        <mesh geometry={nodes.Cube089.geometry} material={materials['Wood.001']} />
        <mesh geometry={nodes.Cube089_1.geometry} material={materials['Orange.003']} />
      </group>
      <group position={[-6.859, 1.419, -5.081]} rotation={[-0.027, -0.004, 0.075]}>
        <mesh geometry={nodes.Cube090.geometry} material={materials['Wood.003']} />
        <mesh geometry={nodes.Cube090_1.geometry} material={materials['Orange.006']} />
        <mesh geometry={nodes.Cube090_2.geometry} material={materials['LightOrange.005']} />
      </group>
      <mesh geometry={nodes.Grass.geometry} material={materials['Green.008']} position={[-3.957, 1.311, 4.75]} rotation={[0.067, 0.002, 0.045]} />
      <group position={[3.687, 3.475, -1.1]} rotation={[0.044, 0.002, 0.01]} scale={0.822}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['Wood.006']} />
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.LightWood} />
        <mesh geometry={nodes.Cylinder009_2.geometry} material={materials.Fire} />
      </group>
      <group position={[12.942, 3.448, -2.934]} rotation={[-0.009, 0, -0.024]} scale={13.593}>
        <mesh geometry={nodes.Cube021.geometry} material={materials['Rock.003']} />
        <mesh geometry={nodes.Cube021_1.geometry} material={materials.Green} />
      </group>
      <mesh geometry={nodes.Rock_6.geometry} material={materials['Rock.004']} position={[13.118, 3.032, -10.842]} rotation={[-0.016, 0, -0.007]} scale={7.912} />
      <group position={[0.834, 3.48, -12.985]} rotation={[-0.016, 0, -0.031]} scale={3.263}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Rock.005']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['moss.green']} />
      </group>
      <group position={[0.507, 1.798, -8.37]} rotation={[0.067, 0, 0.052]} scale={3.126}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Rock.005']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['moss.green']} />
      </group>
      <group position={[7.551, 3.454, -9.848]} rotation={[-0.035, 0, 0.028]} scale={1.55}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Green.011']} />
      </group>
      <group position={[5.364, 3.595, -9.798]} rotation={[-0.136, 0, -0.073]}>
        <mesh geometry={nodes.Cylinder064.geometry} material={materials['Wood.007']} />
        <mesh geometry={nodes.Cylinder064_1.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cylinder064_2.geometry} material={materials['LightWood.001']} />
      </group>
      <group position={[10.526, 3.501, -5.885]} rotation={[-0.016, 0, -0.031]}>
        <mesh geometry={nodes.Cylinder062.geometry} material={materials['Wood.008']} />
        <mesh geometry={nodes.Cylinder062_1.geometry} material={materials['Orange.001']} />
        <mesh geometry={nodes.Cylinder062_2.geometry} material={materials.LightOrange} />
      </group>
      <mesh geometry={nodes.Plant_4001.geometry} material={materials['Green.012']} position={[6.798, 3.74, 1.453]} rotation={[-0.015, 0, 0.09]} />
      <group position={[8.459, 3.653, -1.833]} rotation={[-0.016, 0, -0.031]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Pink.001']} />
      </group>
      <group position={[2.741, 3.682, -10.01]} rotation={[-0.016, 0, -0.074]}>
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['Wood.009']} />
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Green.013']} />
      </group>
      <group position={[1.384, 1.203, 2.046]} rotation={[-0.002, 0, -0.025]} scale={1.05}>
        <mesh geometry={nodes.Cube070.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube070_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cube070_2.geometry} material={materials['Green.014']} />
        <mesh geometry={nodes.Cube070_3.geometry} material={materials['DarkGreen.005']} />
      </group>
      <group position={[2.983, 1.24, 3.45]} rotation={[0, 0, -0.017]}>
        <mesh geometry={nodes.Cube080.geometry} material={materials['White.001']} />
        <mesh geometry={nodes.Cube080_1.geometry} material={materials['Black.001']} />
        <mesh geometry={nodes.Cube080_2.geometry} material={materials['Orange.002']} />
        <mesh geometry={nodes.Cube080_3.geometry} material={materials['LightWood.003']} />
      </group>
      <group position={[5.88, 3.438, -0.604]} rotation={[0.026, -0.004, 0.01]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Wood.010']} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Green.015']} />
        <mesh geometry={nodes.Cylinder011_2.geometry} material={materials.Mushroom_Top} />
        <mesh geometry={nodes.Cylinder011_3.geometry} material={materials.Mushroom_Bottom} />
        <mesh geometry={nodes.Cylinder011_4.geometry} material={materials['DarkGreen.006']} />
      </group>
      <group position={[-11.905, 1.002, -1.162]} rotation={[-0.004, -0.033, 0.096]}>
        <mesh geometry={nodes.Plane029.geometry} material={materials['Green.016']} />
        <mesh geometry={nodes.Plane029_1.geometry} material={materials.Cyan} />
        <mesh geometry={nodes.Plane029_2.geometry} material={materials['Yellow.001']} />
      </group>
      <mesh geometry={nodes.Grass001.geometry} material={materials['Green.018']} position={[-4.758, 1.274, 9.464]} rotation={[0.04, 0, 0.07]} />
      <mesh geometry={nodes.Grass002.geometry} material={materials['Green.018']} position={[2.035, 1.199, 2.631]} rotation={[0, 0, -0.017]} />
      <mesh geometry={nodes.Grass003.geometry} material={materials['Green.018']} position={[-4.28, 1.285, 10.026]} rotation={[0.04, 0, 0.07]} />
      <group position={[12.778, 5.454, 2.192]} rotation={[0.038, 0, -0.032]}>
        <mesh geometry={nodes.Cube044.geometry} material={materials['Green.017']} />
        <mesh geometry={nodes.Cube044_1.geometry} material={materials['Berry.002']} />
      </group>
      <group position={[-8.916, 1.088, -7.708]} rotation={[0.015, -0.002, 0.076]} scale={1.603}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Wood.013']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Green.019']} />
      </group>
      <group position={[-9.403, 1.179, -5.2]} rotation={[-0.027, 0, 0.075]}>
        <mesh geometry={nodes.Cylinder061.geometry} material={materials['Wood.014']} />
        <mesh geometry={nodes.Cylinder061_1.geometry} material={materials['Orange.007']} />
        <mesh geometry={nodes.Cylinder061_2.geometry} material={materials['LightOrange.001']} />
      </group>
      <group position={[-10.297, 1.053, 1.9]} rotation={[0.282, -1.182, 0.262]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Wood.012']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Mushroom_Top.001']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials['Mushroom_Bottom.001']} />
      </group>
      <group position={[-7.111, 0.996, 11.247]} rotation={[-0.027, 0, 0.075]} scale={1.581}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Wood.014']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Orange.007']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['LightOrange.001']} />
      </group>
      <group position={[1.839, 1.517, 11.694]} rotation={[0.015, 0, 0.076]} scale={1.317}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Wood.002']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[4.872, 3.684, -3.993]} rotation={[0.097, -0.703, 0.062]} scale={0.605}>
        <mesh geometry={nodes.Cylinder020.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Cylinder020_1.geometry} material={materials['Black.005']} />
        <mesh geometry={nodes.Cylinder020_2.geometry} material={materials.LightGreen} />
        <mesh geometry={nodes.Cylinder020_3.geometry} material={materials['Green.009']} />
      </group>
      <mesh geometry={nodes.Low_Poly_Watchtower.geometry} material={materials.Atlas} position={[-3.956, 1.284, -5.846]} rotation={[-1.549, 0.003, -2.914]} scale={0.56} />
      <mesh geometry={nodes.Instrument_Guitar_Ultra_Low_Poly.geometry} material={materials.Meshessipropinstrumentguitar041Mtl} position={[-4.016, 4.603, -5.55]} rotation={[-0.726, 0.137, 0.988]} scale={0.134} />
      <group position={[-3.216, 0.957, 6.798]} rotation={[-0.003, 1.367, 0.015]} scale={0.125}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Wood.015']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['LightWood.004']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.String} />
      </group>
      <mesh geometry={nodes.Handpainted_ladder.geometry} material={materials['ladder-brown']} position={[1.631, 2.757, -3.053]} />
      <mesh geometry={nodes.Office_desk_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[10.654, 1.614, 11.744]} rotation={[Math.PI, -0.37, Math.PI]} scale={0.715} />
      <mesh geometry={nodes.Cube000_ComputerDesk_0.geometry} material={materials.ComputerDesk} position={[10.613, 1.601, 11.177]} rotation={[-3.12, 0.299, -3.124]} scale={0.575} />
      <group position={[10.806, 1.847, 11.189]} rotation={[0, -1.419, 0]} scale={0.802}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.desktop_glass} />
        <mesh geometry={nodes.Object_2_1.geometry} material={materials.desktop_case} />
        <mesh geometry={nodes.Object_2_2.geometry} material={materials.desktop_fans} />
        <mesh geometry={nodes.Object_2_3.geometry} material={materials.desktop_parts} />
      </group>
      <mesh geometry={nodes.Monitor.geometry} material={materials.Monitor} position={[10.62, 2.14, 11.763]} rotation={[-1.573, -0.015, -1.174]} scale={0.852} />
      <mesh geometry={nodes.Low_Poly_Coffee_table.geometry} material={materials.base_color} position={[13.264, 1.477, 8.684]} rotation={[-0.133, -1.083, -0.103]} scale={0.103} />
      <mesh geometry={nodes['Low_Poly,_Old-Style_Couch'].geometry} material={materials['Material.001']} position={[10.846, 1.509, 9.661]} rotation={[-2.996, 1.127, 3.025]} scale={[0.771, 0.033, 0.257]} />
      <group position={[2.759, 3.541, -2.243]} rotation={[-0.999, 1.452, 1.07]} scale={[0.15, 0.05, 0.1]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['Lovsamling-pages']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['lovsamling-image-text']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['lovsamling-red']} />
      </group>
      <group position={[-11.011, 2.822, 8.914]} rotation={[-0.052, 1.121, 0.085]}>
        <mesh geometry={nodes.Cube_Latern_01_M_0_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_5.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-6.289, 3.267, 1.721]} rotation={[-0.099, 1.251, 0.125]}>
        <mesh geometry={nodes.Cube_Latern_01_M_0_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube_Latern_01_M_0_5.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes['Chair_-_low_poly'].geometry} material={materials.Chair} position={[-3.955, 4.373, -5.793]} rotation={[-1.569, -0.015, -2.974]} scale={0.263} />
      <mesh geometry={nodes.Low_Poly_Lantern.geometry} material={materials['LANTERN_MAT_FINAL.002']} position={[-3.369, 4.341, -5.493]} rotation={[0.009, -1.343, -0.013]} scale={0.06} />
      <group position={[-7.393, 1.988, 11.276]} rotation={[-Math.PI, 1.058, -Math.PI]} scale={[-0.244, -0.29, -0.024]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Jens Osberg - farger']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Black.001']} position={[-7.422, 2.157, 11.215]} rotation={[0.387, -1.022, -1.371]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Ground} position={[8.387, 1.122, 10.928]} />
      <group position={[-4.613, 4.456, -4.836]}>
        <mesh geometry={nodes.Object_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_1_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_1_2.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_1_3.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_1_4.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/my-island.glb')
