// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Minimap({ minimapClicked, setMinimapClicked }) {
    const { nodes, materials } = useGLTF("/minimap.glb");
    return (
        <group scale={4} setCameraPosition={null} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Om_meg.geometry}
                material={nodes.Om_meg.material}
                position={[0.03, -0.02, 0.03]}
                rotation={[1.98, -0.27, 0.36]}
                scale={0.03}
                onClick={() => setMinimapClicked(["about", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Juss.geometry}
                material={nodes.Juss.material}
                position={[-0.11, 0.1, -0.03]}
                rotation={[1.78, 0, 0.21]}
                scale={0.05}
                onClick={() => setMinimapClicked(["law", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Musikk.geometry}
                material={nodes.Musikk.material}
                position={[-0.17, 0, 0]}
                rotation={[1.89, 0.35, -0.22]}
                scale={0.04}
                onClick={() => setMinimapClicked(["music", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Teknologi.geometry}
                material={nodes.Teknologi.material}
                position={[0.02, 0.1, -0.02]}
                rotation={[1.83, 0.02, 0.19]}
                scale={0.04}
                onClick={() => setMinimapClicked(["tech", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Styr_kameraet_selv.geometry}
                material={nodes.Styr_kameraet_selv.material}
                position={[-0.16, -0.05, 0.02]}
                rotation={[1.08, 0.11, 0.16]}
                scale={0.02}
                onClick={() => setMinimapClicked(["start", true, false])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Om_meg_kart.geometry}
                material={materials.kartutsnitt}
                onClick={() => setMinimapClicked(["about", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Teknologi_kart.geometry}
                material={materials.kartutsnitt}
                onClick={() => setMinimapClicked(["tech", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Juss_kart.geometry}
                material={materials.kartutsnitt}
                onClick={() => setMinimapClicked(["law", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Musikk_kart.geometry}
                material={materials.kartutsnitt}
                onClick={() => setMinimapClicked(["music", true, true])}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Styr_kamera_kart.geometry}
                material={materials.kartutsnitt}
                onClick={() => setMinimapClicked(["start", true, false])}
            />
        </group>
    );
}

useGLTF.preload("/minimap.glb");