import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Main from '../components/Main'
import Navbar from '../components/Navbar'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jens | Jurist og teknolog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/jenslogo.ico" />
      </Head>
      <Navbar />
      <Main />
    </div>
  )
}

export default Home
